yatube/posts/urls.py
# posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('index/', views.index, name='index'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace = 'posts')),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True, null=True,
    )

   

class Group(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique='slug')
    description = models.TextField()
    
    def __str__(self):
        return self.title

# Create your models here.

yatube/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404 
from .models import Post, Group

def index(request):
    title = 'Главная страница ютуб'
    text = 'Здесь будет главная страница ютуб'
    template = 'posts/index.html' 
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
        'title': title, 
        'text': text,
    }
    return render(request, template, context)

def group_posts(request, slug):
    title = 'Главная страница ютуб'
    text = 'Здесь будет главная страница ютуб'
    group = get_object_or_404(Group, slug=slug)
    template = 'posts/group_list.html'
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'title': title, 
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)
# Create your views here.

yatube/templates/base.html
{% load static %}
  
  <!DOCTYPE html> <!-- Используется html 5 версии -->
  <html lang="ru"> <!-- Язык сайта - русский -->
    <head>    
      <meta charset="utf-8"> <!-- Кодировка сайта -->
      <!-- Сайт готов работать с мобильными устройствами -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Загружаем фав-иконки -->
      <link rel="icon" href="img/fav/fav.ico" type="image">
      <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
      <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
      <meta name="msapplication-TileColor" content="#000">
      <meta name="theme-color" content="#ffffff">
      <!-- Подключен файл со стандартными стилями бустрап -->
      <link rel="stylesheet" href="css/bootstrap.min.css">
      <title>{{ title }}</title>
      </head>
      <body>   
      <header>
        {% include 'includes/header.html' %}
      </header>
      <main>
        {% block content %}
         Контент не подвезли :(
        {% endblock %}
     </main>
      <footer>
        {% include 'includes/footer.html' %} 
      </footer>
    </body>
  </html> 

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
      <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>

yatube/templates/includes/header.html
{% load static %}
<header>
      <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
      <!-- В дальнейшем тут будет создано полноценное меню -->
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="{% url 'posts:index' %}">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
            <span style="color:red">Ya</span>tube</a>
          </a>
        </div>
      </nav>      
    </header>
    

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{text}}</h1>
  <title> {{title}} </title>
  <p> {{ group.description }} </p>
  {% for post in posts %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text|linebreaksbr }}</p>    
  {% if not forloop.last %}<hr>{% endif %}
{% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block content %}
  <h1>{{text}}</h1>
  <title> {{title}} </title>
  {% for post in posts %}
   <ul>
     <li>
       Автор: {{ post.author.get_full_name }}
     </li>
     <li>
       Дата публикации: {{ post.pub_date|date:"d E Y" }}
     </li>
   </ul>
   <p>{{ post.text }}</p>
   {% if post.group.slug %}    
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}